# Generated by Django 3.1.5 on 2021-01-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='instock',
        ),
    ]
