# Generated by Django 3.1.5 on 2021-02-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210114_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipped',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
