# Generated by Django 3.1.5 on 2021-02-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210209_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
