# Generated by Django 3.1.5 on 2021-02-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210209_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quant',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=7, null=True),
        ),
    ]
